//
// Created by szterg_r on 22/08/2017.
//

#ifndef CORE_CONFIG_DETAILS_LINUXCONFIG_HPP
#define CORE_CONFIG_DETAILS_LINUXCONFIG_HPP

#define USING_LINUX

#endif //CORE_CONFIG_DETAILS_LINUXCONFIG_HPP
