//
// Created by szterg_r on 22/08/2017.
//

#ifndef CORE_CONFIG_DETAILS_WINDOWSCONFIG_HPP
#define CORE_CONFIG_DETAILS_WINDOWSCONFIG_HPP

#define USING_WINDOWS

#endif //CORE_CONFIG_DETAILS_WINDOWSCONFIG_HPP
